name: CI

on:
  release:
    types:
      - created
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test semver-diff
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: test
        run: |
          echo "${{ toJSON(github.event.pull_request) }}"
      - name: Run semver-diff
        id: semver-diff
        uses: ./
      - name: Show release type
        run: |
          echo "Release type: ${{ steps.semver-diff.outputs.release_type }}"
